project_id = "ilqhmdyjrstajgnfyjyg"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.mp-create-payment]
verify_jwt = false

[functions.mp-installments]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false
